---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/connections":
    get:
      summary: Retrieves the connections of a talent
      tags:
      - Connections
      parameters:
      - name: id
        in: query
        description: Wallet address or username
        schema:
          type: string
      - name: keyword
        in: query
        description: Keyword search to filter by the connected user name
        schema:
          type: string
      - name: connection_type
        in: query
        schema:
          type: string
          enum:
          - super_connection
          - supporter
          - supporting
          - mutual_subscription
          - subscriber
          - subscribing
        description: Filter by a specific connection type
      - name: cursor
        in: query
        description: The cursor to fetch the next page
        schema:
          type: string
      - name: X-API-KEY
        in: header
        description: Your Talent Protocol API key
        schema:
          type: string
      responses:
        '200':
          description: talent found
          content:
            application/json:
              example:
                connections:
                - connected_at: '2023-03-22T15:23:39.000Z'
                  connected_user_invested_amount: '0'
                  connection_type: super_connection
                  id: 2a7b1316-8646-49c9-a7c0-070f42fbad26
                  name: user88
                  profile_picture_url:
                  ticker:
                  user_invested_amount: '0'
                  username: user88
                  wallet_address: 6dd07cb43136af1a9388ce6244281d3a
                - connected_at: '2023-03-22T15:23:39.000Z'
                  connected_user_invested_amount: '0'
                  connection_type: supporter
                  id: a131bc21-76bb-48bd-8fdb-3f11d05e1e50
                  name: user89
                  profile_picture_url:
                  ticker:
                  user_invested_amount: '0'
                  username: user89
                  wallet_address: 237e17e5ce092ef3b63b258db163a9b4
                - connected_at: '2023-03-22T15:23:39.000Z'
                  connected_user_invested_amount: '0'
                  connection_type: supporting
                  id: 650068fa-8010-4254-8928-36670f204770
                  name: user90
                  profile_picture_url:
                  ticker:
                  user_invested_amount: '0'
                  username: user90
                  wallet_address: c2aa639bb65edb008dfdaf599ed4c426
                - connected_at: '2023-03-22T15:23:39.000Z'
                  connected_user_invested_amount: '0'
                  connection_type: subscriber
                  id: 986b7bbd-1f65-4ebb-940d-cde88a3d33af
                  name: user91
                  profile_picture_url:
                  ticker:
                  user_invested_amount: '0'
                  username: user91
                  wallet_address: 7455de4a6bf456d6eb11e64bbbaf6067
                pagination:
                  total: 4
                  cursor:
              schema:
                type: object
                properties:
                  connections:
                    type: array
                    items:
                      type: object
                      properties:
                        username:
                          type: string
                          description: The username of the connected user
                        name:
                          type: string
                          description: The name of the connected user
                        wallet_address:
                          type: string
                          description: The wallet address of the connected user
                        user_invested_amount:
                          type: string
                          description: The amount invested by the user
                        connected_user_invested_amount:
                          type: string
                          description: The amount invested by the connected user
                        connection_type:
                          type: string
                          enum:
                          - super_connection
                          - supporter
                          - supporting
                          - mutual_subscription
                          - subscriber
                          - subscribing
                          description: The type of the connection
                        connected_at:
                          type: string
                          format: datetime
                          description: The timestamp of the initial date the users
                            connected
                        profile_picture_url:
                          type: string
                          nullable: true
                          description: The profile picture of the connected user
                        ticker:
                          type: string
                          nullable: true
                          description: The token ticker of the connected user
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                        description: The total amount of records
                      cursor:
                        type: string
                        description: The cursor to fetch the next page of records
                        nullable: true
        '404':
          description: talent not found
        '401':
          description: unauthorized request
  "/subscribers":
    get:
      summary: Retrieves the subscribers of a talent
      tags:
      - Subscribers
      parameters:
      - name: id
        in: query
        description: Wallet address or username
        schema:
          type: string
      - name: cursor
        in: query
        description: The cursor to fetch the next page
        schema:
          type: string
      - name: X-API-KEY
        in: header
        description: Your Talent Protocol API key
        schema:
          type: string
      responses:
        '200':
          description: talent found
          content:
            application/json:
              example:
                subscribers:
                - email: user_126@talentprotocol.com
                  headline:
                  name: user126
                  profile_picture_url:
                  username: user126
                  wallet_address: 0e7a52df6dec25cb2da69f20a7e88ff2
                - email: user_127@talentprotocol.com
                  headline:
                  name: user127
                  profile_picture_url:
                  username: user127
                  wallet_address: 80e647fc168d808c4028e650773c042d
                pagination:
                  total: 2
                  cursor:
              schema:
                type: object
                properties:
                  subscribers:
                    type: array
                    items:
                      type: object
                      properties:
                        username:
                          type: string
                        name:
                          type: string
                        headline:
                          type: string
                          nullable: true
                        profile_picture_url:
                          type: string
                          nullable: true
                        email:
                          type: string
                        wallet_address:
                          type: string
                          nullable: true
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                        description: The total amount of records
                      cursor:
                        type: string
                        description: The cursor to fetch the next page of records
                        nullable: true
        '404':
          description: talent not found
        '401':
          description: unauthorized request
  "/subscribing":
    get:
      summary: Retrieves the talents a talent is subscribing
      tags:
      - Subscribing
      parameters:
      - name: id
        in: query
        description: Wallet address or username
        schema:
          type: string
      - name: cursor
        in: query
        description: The cursor to fetch the next page
        schema:
          type: string
      - name: X-API-KEY
        in: header
        description: Your Talent Protocol API key
        schema:
          type: string
      responses:
        '200':
          description: talent found
          content:
            application/json:
              example:
                subscribing:
                - email: user_136@talentprotocol.com
                  headline:
                  name: user136
                  profile_picture_url:
                  username: user136
                  wallet_address: '02119da1bb3dd254876744d159a539ff'
                - email: user_135@talentprotocol.com
                  headline:
                  name: user135
                  profile_picture_url:
                  username: user135
                  wallet_address: 6e6d549cd29920f588ca730522431606
                pagination:
                  total: 2
                  cursor:
              schema:
                type: object
                properties:
                  subscribing:
                    type: array
                    items:
                      type: object
                      properties:
                        username:
                          type: string
                        name:
                          type: string
                        headline:
                          type: string
                          nullable: true
                        profile_picture_url:
                          type: string
                          nullable: true
                        email:
                          type: string
                        wallet_address:
                          type: string
                          nullable: true
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                        description: The total amount of records
                      cursor:
                        type: string
                        description: The cursor to fetch the next page of records
                        nullable: true
        '404':
          description: talent not found
        '401':
          description: unauthorized request
  "/supporters":
    get:
      summary: Retrieves the supporters of a talent
      tags:
      - Supporters
      parameters:
      - name: id
        in: query
        description: Wallet address or username
        schema:
          type: string
      - name: cursor
        in: query
        description: The cursor to fetch the next page
        schema:
          type: string
      - name: X-API-KEY
        in: header
        description: Your Talent Protocol API key
        schema:
          type: string
      responses:
        '200':
          description: talent found
          content:
            application/json:
              example:
                supporters:
                - email: user_167@talentprotocol.com
                  headline:
                  name: user167
                  profile_picture_url:
                  username: user167
                  wallet_address: c907e984186f817e4d442e77e71d1e5f
                - email: user_168@talentprotocol.com
                  headline:
                  name: user168
                  profile_picture_url:
                  username: user168
                  wallet_address: '0379c2b0904afbb3cad6fdd79f34d2d7'
                pagination:
                  total: 2
                  cursor:
              schema:
                type: object
                properties:
                  supporters:
                    type: array
                    items:
                      type: object
                      properties:
                        username:
                          type: string
                        name:
                          type: string
                        headline:
                          type: string
                          nullable: true
                        profile_picture_url:
                          type: string
                          nullable: true
                        email:
                          type: string
                        wallet_address:
                          type: string
                          nullable: true
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                        description: The total amount of records
                      cursor:
                        type: string
                        description: The cursor to fetch the next page of records
                        nullable: true
        '404':
          description: talent not found
        '401':
          description: unauthorized request
  "/talents":
    get:
      summary: Retrieves a list of talents
      tags:
      - Talents
      parameters:
      - name: ids[]
        in: query
        schema:
          type: array
          items:
            type: string
        description: List of wallet addresses or usernames
      - name: cursor
        in: query
        description: The cursor to fetch the next page
        schema:
          type: string
      - name: X-API-KEY
        in: header
        description: Your Talent Protocol API key
        schema:
          type: string
      responses:
        '200':
          description: get all talents
          content:
            application/json:
              example:
                talents:
                - email: user_176@talentprotocol.com
                  headline:
                  name: user176
                  profile_picture_url:
                  username: user176
                  wallet_address: 1eff98675f1a490ef7416125d251e576
                - email: user_178@talentprotocol.com
                  headline:
                  name: user178
                  profile_picture_url:
                  username: user178
                  wallet_address: f6f1cc6037bda0687f818e53088b7fd1
                - email: user_175@talentprotocol.com
                  headline:
                  name: user175
                  profile_picture_url:
                  username: user175
                  wallet_address: 96b7e805d3fb4f7fc69db10cb06be5d4
                - email: user_177@talentprotocol.com
                  headline:
                  name: user177
                  profile_picture_url:
                  username: user177
                  wallet_address: 6a2da620e6c37123f745b50c005bc6c7
                pagination:
                  total: 4
                  cursor:
              schema:
                type: object
                properties:
                  talents:
                    type: array
                    items:
                      type: object
                      properties:
                        username:
                          type: string
                        name:
                          type: string
                        headline:
                          type: string
                          nullable: true
                        profile_picture_url:
                          type: string
                          nullable: true
                        email:
                          type: string
                        wallet_address:
                          type: string
                          nullable: true
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                        description: The total amount of records
                      cursor:
                        type: string
                        description: The cursor to fetch the next page of records
                        nullable: true
        '401':
          description: unauthorized request
  "/talents/{id}":
    get:
      summary: Retrieves a talent
      tags:
      - Talents
      parameters:
      - name: id
        in: path
        description: Wallet address or username
        required: true
        schema:
          type: string
      - name: X-API-KEY
        in: header
        description: Your Talent Protocol API key
        schema:
          type: string
      responses:
        '200':
          description: talent found
          content:
            application/json:
              example:
                talent:
                  email: user_187@talentprotocol.com
                  headline:
                  name: API user
                  profile_picture_url:
                  subscribers_count: 1
                  subscribing_count: 2
                  supporters_count: 1
                  supporting_count: 1
                  username: user187
                  wallet_address: c24a13b73248f61bf15d3e99a942303f
              schema:
                type: object
                properties:
                  talent:
                    type: object
                    properties:
                      username:
                        type: string
                      name:
                        type: string
                      headline:
                        type: string
                        nullable: true
                      profile_picture_url:
                        type: string
                        nullable: true
                      email:
                        type: string
                      wallet_address:
                        type: string
                        nullable: true
        '404':
          description: talent not found
        '401':
          description: unauthorized request
servers:
- url: https://{defaultHost}/api/v1
  variables:
    defaultHost:
      default: api.talentprotocol.com
