default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" }%>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: mvp_development

test:
  <<: *default
  database: mvp_test

production:
  <<: *default
  database: mvp_production
  username: mvp
  password: <%= ENV['MVP_DATABASE_PASSWORD'] %>
