meta_product_name: "Talent Protocol"
meta_title: "Talent Protocol - Beta"
meta_description: "Talent Protocol is a web3 professional network where the next generation of builders can share their goals and find the support they need to succeed."
meta_image: "/metaimage.jpg?1"
meta_card_type: "summary_large_image"
