:logfile: log/sidekiq.log
:queues:
  - critical
  - high
  - default
  - mailers
  - low
:schedule:
  send_token_launch_reminder:
    cron: '0 5 * * 4'   # Runs once every thursday at 5pm
    class: SendTokenLaunchReminderJob
